import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <style jsx>
        {
          `
          .popularBlogs{
            margin:50px 0px;
          }
          `
        }
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>

        <div className={styles.center}>
          <h1 className={styles.myClass}>Hunting Coders</h1>
          <div className={styles.imagewrap}>
            <img className={styles.myimg} src="/Images/homeimg.jpg" alt="hunting coder image" width={437}
              height={258}/>
          </div>
          <p >A blog for hunting Coders by a hunting Coder. Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum delectus iusto nemo cumque officiis, tempore placeat id voluptates magnam eius quisquam! Soluta, assumenda?</p>
        </div>
      </main>
    </>
  )
}
