import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <style jsx>
        {
          `
          .popularBlogs{
            margin:50px 0px;
          }
          `
        }
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>

        <div className={styles.center}>
          <h1 className={styles.myClass}>Hunting Coders</h1>
          <div className={styles.imagewrap}>

            <Image className={styles.myimg} src='/Images/homeimg.jpg'
              width={437}
              height={258}
            />
          </div>
          <p >A blog for hunting Coders by a hunting Coder.</p>
        </div>
      </main>
    </>
  )
}
