import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.container}>
        <ul>
          <li className={styles.mxclass}>Home</li>
          <li className={styles.mxclass}>About</li>
          <li className={styles.mxclass}>Blog</li>
          <li className={styles.mxclass}>Contact Us</li>
        </ul>
      </nav>
      <main className={`${styles.main} ${inter.className}`}>

        <div className={styles.center}>
          <h1 className={styles.myClass}>Hunting Coders</h1>
          <p >A blog for hunting Coders by a hunting Coder.</p>
        </div>
        <h2>Popular Blogs</h2>
        <div className={styles.grid}>
          <div className="container">
            <h3>How to learn the javascript language ?</h3>
            <p>This is the blog about learning the javascript for preparing the learning for the react js framework.</p>
          </div>
          <div className="container">
            <h3>How to learn the javascript language ?</h3>
            <p>This is the blog about learning the javascript for preparing the learning for the react js framework.</p>
          </div>
          <div className="container">
            <h3>How to learn the javascript language ?</h3>
            <p>This is the blog about learning the javascript for preparing the learning for the react js framework.</p>
          </div>
          <div className="container">
            <h3>How to learn the javascript language ?</h3>
            <p>This is the blog about learning the javascript for preparing the learning for the react js framework.</p>
          </div>
        </div>
      </main>
    </>
  )
}
